### ISSUE TITLE
Adding Malay Language Translation

### ISSUE THREAD

**Issue by EugeneGohh** [dephraiim/awesome-developer-dictionary#33]
I'm a Malaysian. Can I contribute to this by translating README.md to Malay version?

**Comment by shahbazalam07** [comment]
I want to work on this issue

**Comment by EugeneGohh** [comment]
> I want to work on this issue

You're welcome to do so, we can work on it together translating to Bahasa Melayu.

**Comment by dephraiim** [comment]
Thanks guys, if you're done, mention me and I'll merge it

**Comment by EugeneGohh** [comment]
@dephraiim Alright I just forked it, I'll probably do it later.

**Comment by EugeneGohh** [comment]
@dephraiim Hello, I have done the Malay Translation. 

> https://github.com/EugeneGohh/awesome-developer-dictionary/blob/master/README-ms.md

**Comment by EugeneGohh** [comment]
Have a nice day @dephraiim goanna close this issue.
